#Directory principale del progetto
baseDir=../TimeStamp/
#Directory che contiene tutti file java per cui generare il prompt
sourceCodeDir=TimeStampSourceCode/
#Scenari diversi che può avere una certa classe, se si usa un'unica versione della classe lasciare solo original
scenarios=original
#Percorso della directory in cui verrà salvato il prompt.
outputDir=LLM_Test/TimeStampPrompt/input/
#Numero di test da generare per ogni prompt
numberOfTests=ten