#Directory principale del progetto
baseDir=../103_sweethome3d/
#Directory che contiene tutti file java per cui generare il prompt
sourceCodeDir=src/main/java/com/eteks/sweethome3d/
#Scenari diversi che può avere una certa classe, se si usa un'unica versione della classe lasciare solo original
scenarios=original
#Percorso della directory in cui verrà salvato il prompt.
outputDir=LLM_Test/Prompt/input/
#Numero di test da generare per ogni prompt
numberOfTests=ten