// DefaultNoteListModel_1Test.java
package com.allenstudio.ir.ui;

import com.allenstudio.ir.core.plugins.AbstractNote;
import com.allenstudio.ir.event.NoteListDataEvent;
import com.allenstudio.ir.event.NoteListDataListener;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link DefaultNoteListModel}.
* It contains one unit test case for the {@link DefaultNoteListModel#size()} method.
*/
class DefaultNoteListModel_1Test {
		// DefaultNoteListModel.java
//
// UnitTest class is generated by jUnit JDust unit test builder

// public DefaultNoteListModel_1Test(TestCase.Reference reference) {
//    super(reference);
// }
//
//
// @Test
// public void test_DefaultNoteListModel_1_size() throws Exception {
//
//     Vector empty = new ArrayList();
//     AbstractNote emptyAsynNote = new Vector()
//              .addElement(new AbstractNote() {});
//     NoteListModel m1 = new DefaultNoteListModel(
//               new ArrayVector(),
//               new ArrayVector(),
//               new ArrayList(),
//               new ArrayBitSet());
//     assertEquals(0,
//               m1.size());
// }

    // void test_DefaultNoteListModel_1_size() throws Exception{

    /** Vector empty */
    private Vector emptyVector = new ArrayList();
    /** ArrayVector empty */
    private ArrayVector emptyArrayVector = new ArrayVector();
    /** BitSet empty */
    private BitSet emptyBitSet = new BitSet();
    /** ArrayList empty */
    private ArrayList emptyArrayList = new ArrayList();

    /**
	 * Test method for {@link com.allenstudio.ir.ui.DefaultNoteListModel#size()}.
	 */
    //@Test
//  public void test_DefaultNoteListModel_1_size() throws Exception {
//
//    }

}