// SortedListSumTest.java
package scenario1;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
* Test class of {@link SortedListSum}.
* It contains ten unit test cases for the {@link SortedListSum#sortedListSum(List)} method.
*/
class SortedListSumTest {
			// Test case 1
    @Test
    public void testSortedListSum1() {
        List<String> lst = new ArrayList<String>();
        lst.add("abc");
        lst.add("def");
        lst.add("gh");
        lst.add("ijk");
        lst.add("lmn");
        lst.add("opq");
        lst.add("rst");
        lst.add("uvw");
        lst.add("xyz");
        List<Object> result = SortedListSum.sortedListSum(lst);
        List<Object> expected = new ArrayList<Object>();
        expected.add("gh");
        expected.add("opq");
        expected.add("rst");
        expected.add("abc");
        expected.add("def");
        expected.add("uvw");
        expected.add("ijk");
        expected.add("lmn");
        expected.add("xyz");
        assertEquals(expected, result);
    }
			// Test case 2
    @Test
    public void testSortedListSum2() {
        List<String> lst = new ArrayList<String>();
        lst.add("abc");
        lst.add("def");
        lst.add("gh");
        lst.add("ijk");
        lst.add("lmn");
        lst.add("opq");
        lst.add("rst");
        lst.add("uvw");
        lst.add("xyz");
        lst.add("a");
        lst.add("b");
        lst.add("c");
        lst.add("d");
        lst.add("e");
        lst.add("f");
        lst.add("g");
        lst.add("h");
        lst.add("i");
        lst.add("j");
        lst.add("k");
        lst.add("l");
        lst.add("m");
        lst.add("n");
        lst.add("o");
        lst.add("p");
        lst.add("q");
        lst.add("r");
        lst.add("s");
        lst.add("t");
        lst.add("u");
        lst.add("v");
        lst.add("w");
        lst.add("x");
        lst.add("y");
        lst.add("z");
        List<Object> result = SortedListSum.sortedListSum(lst);
        List<Object> expected = new ArrayList<Object>();
        expected.add("a");
        expected.add("b");
        expected.add("c");
        expected.add("d");
        expected.add("e");
        expected.add("f");
        expected.add("g");
        expected.add("h");
        expected.add("i");
        expected.add("j");
        expected.add("k");
        expected.add("l");
        expected.add("m");
        expected.add("n");
        expected.add("o");
        expected.add("p");
        expected.add("q");
        expected.add("r");
        expected.add("s");
        expected.add("t");
        expected.add("u");
        expected.add("v");
        expected.add("w");
        expected.add("x");
        expected.add("y");
        expected.add("z");
        expected.add("gh");
        expected.add("opq");
        expected.add("rst");
        expected.add("abc");
        expected.add("def");
        expected.add("uvw");
        expected.add("ijk");
        expected.add("lmn");
        expected.add("xyz");
        assertEquals(expected, result);
    }
			// Test case 3
    @Test
    public void testSortedListSum3() {
        List<String> lst = new ArrayList<String>();
        lst.add("abc");
        lst.add("def");
        lst.add("gh");
        lst.add("ijk");
        lst.add("lmn");
        lst.add("opq");
        lst.add("rst");
        lst.add("uvw");
        lst.add("xyz");
        lst.add("a");
        lst.add("b");
        lst.add("c");
        lst.add("d");
        lst.add("e");
        lst.add("f");
        lst.add("g");
        lst.add("h");
        lst.add("i");
        lst.add("j");
        lst.add("k");
        lst.add("l");
        lst.add("m");
        lst.add("n");
        lst.add("o");
        lst.add("p");
        lst.add("q");
        lst.add("r");
        lst.add("s");
        lst.add("t");
        lst.add("u");
        lst.add("v");
        lst.add("w");
        lst.add("x");
        lst.add("y");
        lst.add("z");
        lst.add("ab");
        lst.add("cd");
        lst.add("ef");
        lst.add("gh");
        lst.add("ij");
        lst.add("kl");
        lst.add("mn");
        lst.add("op");
        lst.add("qr");
        lst.add("st");
        lst.add("uv");
        lst.add("wx");
        lst.add("yz");
        List<Object> result = SortedListSum.sortedListSum(lst);
        List<Object> expected = new ArrayList<Object>();
        expected.add("a");
        expected.add("b");
        expected.add("c");
        expected.add("d");
        expected.add("e");
        expected.add("f");
        expected.add("g");
        expected.add("h");
        expected.add("i");
        expected.add("j");
        expected.add("k");
        expected.add("l");
        expected.add("m");
        expected.add("n");
        expected.add("o");
        expected.add("p");
        expected.add("q");
        expected.add("r");
        expected.add("s");
        expected.add("t");
        expected.add("u");
        expected.add("v");
        expected.add("w");
        expected.add("x");
        expected.add("y");
        expected.add("z");
        expected.add("ab");
        expected.add("cd");
        expected.add("ef");
        expected.add("gh");
        expected.add("ij");
        expected.add("kl");
        expected.add("mn");
        expected.add("op");
        expected.add("qr");
        expected.add("st");
        expected.add("uv");
        expected.add("wx");
        expected.add("yz");
        expected.add("gh");
        expected.add("opq");
        expected.add("rst");
        expected.add("abc");
        expected.add("def");
        expected.add("uvw");
        expected.add("ijk");
        expected.add("lmn");
        expected.add("xyz");
        assertEquals(expected, result);
    }
			// Test case 4
    @Test
    public void testSortedListSum4() {
        List<String> lst = new ArrayList<String>();
        lst.add("abc");
        lst.add("def");
        lst.add("gh");
        lst.add("ijk");
        lst.add("lmn");
        lst.add("opq");
        lst.add("rst");
        lst.add("uvw");
        lst.add("xyz");
        lst.add("a");
        lst.add("b");
        lst.add("c");
        lst.add("d");
        lst.add("e");
        lst.add("f");
        lst.add("g");
        lst.add("h");
        lst.add("i");
        lst.add("j");
        lst.add("k");
        lst.add("l");
        lst.add("m");
        lst.add("n");
        lst.add("o");
        lst.add("p");
        lst.add("q");
        lst.add("r");
        lst.add("s");
        lst.add("t");
        lst.add("u");
        lst.add("v");
        lst.add("w");
        lst.add("x");
        lst.add("y");
        lst.add("z");
        lst.add("ab");
        lst.add("cd");
        lst.add("ef");
        lst.add("gh");
        lst.add("ij");
        lst.add("kl");
        lst.add("mn");
        lst.add("op");
        lst.add("qr");
        lst.add("st");
        lst.add("uv");
        lst.add("wx");
        lst.add("yz");
        lst.add("abc");
        lst.add("def");
        lst.add("ghi");
        lst.add("jkl");
        lst.add("mno");
        lst.add("pqr");
        lst.add("stu");
        lst.add("vwx");
        lst.add("yz");
        List<Object> result = SortedListSum.sortedListSum(lst);
        List<Object> expected = new ArrayList<Object>();
        expected.add("a");
        expected.add("b");
        expected.add("c");
        expected.add("d");
        expected.add("e");
        expected.add("f");
        expected.add("g");
        expected.add("h");
        expected.add("i");
        expected.add("j");
        expected.add("k");
        expected.add("l");
        expected.add("m");
        expected.add("n");
        expected.add("o");
        expected.add("p");
        expected.add("q");
        expected.add("r");
        expected.add("s");
        expected.add("t");
        expected.add("u");
        expected.add("v");
        expected.add("w");
        expected.add("x");
        expected.add("y");
        expected.add("z");
        expected.add("ab");
        expected.add("cd");
        expected.add("ef");
        expected.add("gh");
        expected.add("ij");
        expected.add("kl");
        expected.add("mn");
        expected.add("op");
        expected.add("qr");
        expected.add("st");
        expected.add("uv");
        expected.add("wx");
        expected.add("yz");
        expected.add("abc");
        expected.add("def");
        expected.add("ghi");
        expected.add("jkl");
        expected.add("mno");
        expected.add("pqr");
        expected.add("stu");
        expected.add("vwx");
}
}